postgresql version >=10 onwards does not require contrib package
puppetlabs/puppetlabs-puppetdb pull request #350
Opened 2022-02-23 17:58 UTC by KoenDierckx

Fix for https://tickets.puppetlabs.com/browse/PDB-5454

_Started a new PR (to avoid license issue)_

2022-02-23 17:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-puppetdb?pullRequest=350) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-puppetdb?pullRequest=350) before we can accept your contribution.<br/><hr/>**DIERCKXK** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-puppetdb?pullRequest=350) it.</sub>

2022-02-23 20:20 UTC, kenyon commented on manifests/database/postgresql.pp
> +      if (versioncmp($postgres_version, '10') < 0) {
```suggestion
      # from postgresql version 10 onwards, this extension is no longer inside
      # the contrib package, but is being bundled with the postgresql package itself
      if versioncmp($postgres_version, '10') < 0 {
```

2022-04-23 09:22 UTC, ekohl requested changes
I believe this PR is invalid: https://github.com/puppetlabs/puppetlabs-postgresql/commit/10b5d37f6944fa2c2d28f78fdbdfc6d8a3d0acd2 resolved this by making the contrib class a noop if there is no package. This keeps it compatible with distributions where there is still a contrib package.

2022-04-23 09:24 UTC, ekohl commented
Oh, I just realized that's in 8.0.0 and this module isn't marked as compatible so I opened https://github.com/puppetlabs/puppetlabs-puppetdb/pull/353.

2022-04-23 12:00 UTC, merged